### ISSUE TITLE
Build failure with pip

### ISSUE THREAD

**Issue by smackesey** [TileDB-Inc/TileDB-Py#227]
I'm attempting to install tiledb via `pip install tiledb` on macOS Catalina 10.15.1, Python 3.8.0 (installed with asdf version manager). My installation fails with the attached log.

I have very little insight into this problem. My best guess is that it has something to do with XCode developer tools. I have two versions installed-- the ones through the XCode app and the standalone developer tools. I would remove one but I am afraid of breaking other things...

[tiledblog.txt](https://github.com/TileDB-Inc/TileDB-Py/files/3872069/tiledblog.txt)

**Comment by ihnorton** [comment]
Hi @smackesey, thanks for opening the issue. Just to note, I was able to build in a clean environment on macOS 10.14 with `pip install tiledb`.

From the log file, it looks like you have an old version of TileDB (core) installed, which is being detected by the TileDB-Py build script -- at that point it skips building libtiledb from source (lines below from the log file):

```
51 2019-11-20T15:33:37,729     libtiledb_exists found: 'libtiledb.dylib'
...
183 2019-11-20T15:33:42,633   /usr/local/include/tiledb/tiledb.h:3287:15: note: passing argument to parameter 'range_num' here
184 2019-11-20T15:33:42,633       uint64_t* range_num);
185 2019-11-20T15:33:42,633                 ^
186 2019-11-20T15:33:42,644   tiledb/libtiledb.pyx:213:18: error: use of undeclared identifier 'tiledb_query_get_fragment_timestamp_range'
```

This may be from a previous homebrew installation? If you don't want to (or can't) uninstall that version, I just pushed a branch which should allow to force building from source: https://github.com/TileDB-Inc/TileDB-Py/pull/229

```
git clone https://github.com/TileDB-Inc/TileDB-Py
cd TileDB-Py
git checkout ihn/force_tiledb_source <- if the branch is not merged
pip install . --install-option="--tiledb=source"
```

**Comment by smackesey** [comment]
Thanks @ihnorton, I have a homebrew installation of tiledb that is the most recent stable version (1.6.3). If setup.py is looking for an existing installation, shouldn't it be able to use it? Why does it need to build a different tiledb?

**Comment by ihnorton** [comment]
Hi @smackesey, the most recent TileDB release is 1.7, last week, along with TileDB-Py 0.5 which pip is pulling down. The it is not compatible with you 1.6 from homebrew due to API additions. 

brew for 1.7 should be updated shortly: https://github.com/TileDB-Inc/homebrew-stable/pull/27

**Comment by ihnorton** [comment]
@smackesey TileDB from brew is now updated.

**Comment by smackesey** [comment]
Ah I see-- my mistake, I assumed the latest homebrew version was the most recent tiledb. After installing the new TileDB from homebrew I was able to `pip install tiledb` without issue. Thanks!
